version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(levelname)s | %(name)s | %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  stout:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  stderr:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: app.log # Placeholder for log file location

root:
  level: INFO
  handlers: [stout, stderr, file]
