# Form implementation generated from reading ui file 'overtime_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OvertimeWindow:
    def setupUi(self, OvertimeWindow):
        OvertimeWindow.setObjectName("OvertimeWindow")
        OvertimeWindow.resize(475, 656)
        self.verticalLayout = QtWidgets.QVBoxLayout(OvertimeWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_info = QtWidgets.QLabel(parent=OvertimeWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_info.setFont(font)
        self.label_info.setWordWrap(True)
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.label_info)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.date_edit = QtWidgets.QDateEdit(parent=OvertimeWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.date_edit.setFont(font)
        self.date_edit.setCurrentSection(QtWidgets.QDateTimeEdit.Section.DaySection)
        self.date_edit.setCalendarPopup(True)
        self.date_edit.setObjectName("date_edit")
        self.gridLayout.addWidget(self.date_edit, 0, 0, 1, 1)
        self.hours_select = QtWidgets.QDoubleSpinBox(parent=OvertimeWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hours_select.setFont(font)
        self.hours_select.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.hours_select.setDecimals(2)
        self.hours_select.setMinimum(-2000.0)
        self.hours_select.setMaximum(2000.0)
        self.hours_select.setSingleStep(0.5)
        self.hours_select.setObjectName("hours_select")
        self.gridLayout.addWidget(self.hours_select, 0, 1, 1, 1)
        self.save_button = QtWidgets.QPushButton(parent=OvertimeWindow)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_list_view = QtWidgets.QLabel(parent=OvertimeWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_list_view.setFont(font)
        self.label_list_view.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_list_view.setObjectName("label_list_view")
        self.verticalLayout.addWidget(self.label_list_view)
        self.scrollArea = QtWidgets.QScrollArea(parent=OvertimeWindow)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 457, 442))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.list_widget_dates = QtWidgets.QListWidget(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_widget_dates.setFont(font)
        self.list_widget_dates.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.list_widget_dates.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.list_widget_dates.setObjectName("list_widget_dates")
        self.verticalLayout_3.addWidget(self.list_widget_dates)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(OvertimeWindow)
        QtCore.QMetaObject.connectSlotsByName(OvertimeWindow)

    def retranslateUi(self, OvertimeWindow):
        _translate = QtCore.QCoreApplication.translate
        OvertimeWindow.setWindowTitle(_translate("OvertimeWindow", "Manage Overtime Adjustments"))
        self.label_info.setText(
            _translate(
                "OvertimeWindow",
                "<html><head/><body><p>Enter manual changes to your overtime balance, like payouts or expiration. Negative hours reduce your overtime (e.g. -20 for a 20 hour payout), positive hours add to it. Adding a date that already has an entry overwrites its value.</p></body></html>",
            )
        )
        self.date_edit.setDisplayFormat(_translate("OvertimeWindow", "dd/MM/yyyy"))
        self.hours_select.setSuffix(_translate("OvertimeWindow", " h"))
        self.save_button.setText(_translate("OvertimeWindow", "Add"))
        self.label_list_view.setText(_translate("OvertimeWindow", "Overtime Adjustments:"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    OvertimeWindow = QtWidgets.QWidget()
    ui = Ui_OvertimeWindow()
    ui.setupUi(OvertimeWindow)
    OvertimeWindow.show()
    sys.exit(app.exec())
