# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(1200, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container = QtWidgets.QVBoxLayout()
        self.container.setObjectName("container")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_button = QtWidgets.QPushButton(PlotWindow)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.radio_month = QtWidgets.QRadioButton(PlotWindow)
        self.radio_month.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radio_month.setFont(font)
        self.radio_month.setChecked(True)
        self.radio_month.setObjectName("radio_month")
        self.buttonGroup = QtWidgets.QButtonGroup(PlotWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radio_month)
        self.horizontalLayout.addWidget(self.radio_month)
        self.radio_year = QtWidgets.QRadioButton(PlotWindow)
        self.radio_year.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radio_year.setFont(font)
        self.radio_year.setObjectName("radio_year")
        self.buttonGroup.addButton(self.radio_year)
        self.horizontalLayout.addWidget(self.radio_year)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.date_edit = QtWidgets.QDateEdit(PlotWindow)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.date_edit.setFont(font)
        self.date_edit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.date_edit.setCalendarPopup(True)
        self.date_edit.setDate(QtCore.QDate(2020, 7, 1))
        self.date_edit.setObjectName("date_edit")
        self.horizontalLayout.addWidget(self.date_edit)
        self.container.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.container)

        self.retranslateUi(PlotWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "Plot of the Working time"))
        self.save_button.setText(_translate("PlotWindow", "Save"))
        self.radio_month.setText(_translate("PlotWindow", "Month"))
        self.radio_year.setText(_translate("PlotWindow", "Year"))
        self.date_edit.setDisplayFormat(_translate("PlotWindow", "dd/MM/yyyy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotWindow = QtWidgets.QWidget()
    ui = Ui_PlotWindow()
    ui.setupUi(PlotWindow)
    PlotWindow.show()
    sys.exit(app.exec_())
