name: Build and Release with PyInstaller
run-name: Build and Release ${{ github.event.release.tag_name }}

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: timetracker_ubuntu
          - os: windows-latest
            artifact_name: timetracker_win.exe
          - os: macos-latest
            artifact_name: timetracker_mac
    env:
      PYI_NAME: ${{ matrix.artifact_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Build with PyInstaller
        run: uv run pyinstaller installer.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.event.release.tag_name }}
