name: Manual Build with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: stempeluhr_latest_ubuntu
          - os: windows-latest
            artifact_name: stempeluhr_latest_win.exe
          - os: macos-latest
            artifact_name: stempeluhr_latest_mac

    env:
      PYI_NAME: ${{ matrix.artifact_name }}
      UPLOAD_PATH: dist/${{ matrix.artifact_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Build with PyInstaller
        run: uv run pyinstaller installer.spec

      - name: Bundle macOS outputs
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r "${{ matrix.artifact_name }}.zip" "${{ matrix.artifact_name }}" "${{ matrix.artifact_name }}.app"
          echo "UPLOAD_PATH=$(pwd)/${{ matrix.artifact_name }}.zip" >> $GITHUB_ENV

      - name: "Debug: List dist directory"
        run: ls dist/

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ env.UPLOAD_PATH }}
