name: Manual Build with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: timetracker_latest_ubuntu
          - os: windows-latest
            artifact_name: timetracker_latest_win.exe
          - os: macos-latest
            artifact_name: timetracker_latest_mac

    env:
      PYI_NAME: ${{ matrix.artifact_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Build with PyInstaller
        run: uv run pyinstaller installer.spec

      - name: Extract macOS binary
        if: matrix.os == 'macos-latest'
        run: |
          rm dist/${{ matrix.artifact_name }}
          cp dist/${{ matrix.artifact_name }}.app/Contents/MacOS/${{ matrix.artifact_name }} dist/${{ matrix.artifact_name }}
          rm -r dist/${{ matrix.artifact_name }}.app

      - name: "Debug: List dist directory"
        run: ls dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}
