name: Manual Build with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: timetracker_latest_ubuntu
          - os: windows-latest
            artifact_name: timetracker_latest_win.exe
          - os: macos-latest
            artifact_name: timetracker_latest_mac

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install pyinstaller

    - name: Build
      run: >
        pyinstaller
        --onefile
        -w
        --name ${{ matrix.artifact_name }}
        --icon="ui/clock.png"
        --hidden-import="holidays.countries"
        runme.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.artifact_name }}